services:
  postgres-dev:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo_db'
      - 'POSTGRES_PASSWORD=dev_database_passwd'
      - 'POSTGRES_USER=demo_dev_rw'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './db/dev/databases.sql:/docker-entrypoint-initdb.d/1-dev-database.sql'
      - './db/dev/roles.sql:/docker-entrypoint-initdb.d/2-dev-roles.sql'
    networks:
      - 'app-network'

  application:
    build:
      context: '.'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dev:5432/demo_db
      SPRING_DATASOURCE_USERNAME: demo_dev_rw
      SPRING_DATASOURCE_PASSWORD: dev_database_passwd
    depends_on:
      - 'postgres-dev'
    networks:
      - 'app-network'
    entrypoint: >
      sh -c "until nc -z postgres-dev 5432; do echo Waiting for database; sleep 2; done;
             java -jar application.jar"

networks:
  app-network:
    driver: 'bridge'

volumes:
  postgres_data:
