package br.com.transactionauthorizer.constants

object MerchantNames {

    val MEAL_MERCHANTS = listOf(
        "PICPAY*BILHETEUNICO           GOIANIA BR",
        "PICPAY*BILHETEUNICO           RIO DE JANEIRO BR",
        "PICPAY*BILHETEUNICO           SAO PAULO BR",
        "PICPAY*BILHETEUNICO           FORTALEZA BR",
        "PICPAY*BILHETEUNICO           BELO HORIZONTE BR",
        "PICPAY*BILHETEUNICO           CURITIBA BR",
        "PICPAY*BILHETEUNICO           SALVADOR BR",
        "PICPAY*BILHETEUNICO           PORTO ALEGRE BR",
        "PICPAY*BILHETEUNICO           MACEIO BR",
        "PICPAY*BILHETEUNICO           RECIFE BR",
        "PICPAY*BILHETEUNICO           VITORIA BR",
        "PICPAY*BILHETEUNICO           SANTOS BR",
        "PICPAY*BILHETEUNICO           MACAPA BR",
        "PICPAY*BILHETEUNICO           LONDRINA BR",
        "PICPAY*BILHETEUNICO           CUIABA BR",
        "PICPAY*BILHETEUNICO           BELEM BR",
        "PICPAY*BILHETEUNICO           CAMPINAS BR",
        "PICPAY*BILHETEUNICO           NATAL BR",
        "PICPAY*BILHETEUNICO           TERESINA BR"
    )

    val FOOD_MERCHANTS = listOf(
        "SUPERMERCADO DA TERRA  SAO PAULO BR",
        "HORTIFRUTI LIMA       RIO DE JANEIRO BR",
        "MERCADO ALVORADA      BELO HORIZONTE BR",
        "SUPERMARKET PRIMAVERA FORTALEZA BR",
        "HIPERDIA              BRASILIA BR",
        "GIGA GROCERY          CURITIBA BR",
        "SUPER MAIS DIVERSO    PORTO ALEGRE BR",
        "HYPER CESTAS COMPLETAS SALVADOR BR",
        "BIG BAZAR             RECIFE BR",
        "LA VITRINE GROCERY    MACEIO BR",
        "MERCADO MARAPENDI     SAO PAULO BR",
        "HYPER SUPERMAX        RIO DE JANEIRO BR",
        "CESTA FAMILIAR        BELO HORIZONTE BR",
        "SUPERMERCADO BOM PREÇO FORTALEZA BR",
        "VITAMINA GROCERY      BRASILIA BR",
        "MARKETPLACE PRINCESS  CURITIBA BR",
        "BIG BOLSA SUPERMERCADO PORTO ALEGRE BR",
        "SUPERMARKET VIP GROCERY SALVADOR BR",
        "COMPRE MAIS MARKET    RECIFE BR",
        "RAIA GROCERY          MACEIO BR",
        "SUPERMERCADO FALCÃO   SAO PAULO BR",
        "HYPERLOJA             RIO DE JANEIRO BR",
        "VIVER MARKET          BELO HORIZONTE BR"
    )
}